name = "h5fortran-mpi"
description = "Lightweight object-oriented HDF5 MPI parallel interface"
categories = "io"
version = "2.0.2"

[build]
auto-tests = false
external-modules = ["mpi", "hdf5", "h5lt"]

# Linux
link = ["hdf5_openmpihl_fortran", "hdf5_openmpi_fortran", "hdf5_openmpi_hl", "hdf5_openmpi", "z", "mpi_mpifh", "mpi"]

# Windows MSYS2 + MS-MPI
# fpm --flag "-IC:\lib_par\include -IC:\msys64\mingw64\include\" --link-flag "-LC:\lib_par\lib" build
# link = ["hdf5_hl_fortran", "hdf5_fortran", "hdf5_hl_f90cstub", "hdf5_hl", "hdf5_f90cstub", "hdf5", "z", "msmpi"]

[install]
library = true
