name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"
      - "!memcheck.cmake"
      - "!coverage.cmake"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  gcc-new:
    timeout-minutes: 15

    strategy:
      matrix:
        conf: [ { os: ubuntu-latest, mpi: openmpi },
                { os: macos-latest, mpi: open-mpi } ]
#                 { os: ubuntu-24.04, mpi: mpich },  takes like 15 minutes, gives link time warnings

    runs-on: ${{ matrix.conf.os }}

    steps:

    - &python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'

    - name: Python pkgs
      run: pip install numpy h5py

    - name: install MPI (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends lib${{ matrix.conf.mpi }}-dev

    - name: Install HDF5-${{ matrix.conf.mpi }} and MPI (MacOS)
      if: runner.os == 'macOS'
      run: brew install hdf5-mpi ${{ matrix.conf.mpi }}

    - name: GCC (macOS)
      if: runner.os == 'macOS'
      run: |
        echo "CC=gcc-15" >> $GITHUB_ENV
        echo "FC=gfortran-15" >> $GITHUB_ENV

    - &checkout
      uses: actions/checkout@v7

    - name: build and test
      run: cmake --workflow default

    - name: install package
      run: cmake --install build

    - name: example build and test
      run: cmake --workflow default
      working-directory: example
