name: build

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "scripts/CMakeLists.txt"
      - "cmake/libraries.json"
      - ".github/workflows/ci_build.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  linux:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    env:
      CMAKE_INSTALL_PREFIX: ~/libs
      CMAKE_PREFIX_PATH: ~/libs

    steps:

    - name: prereqs (Linux)
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends libopenmpi-dev

    - uses: actions/checkout@v7

    - name: Configure HDF5-MPI
      run: cmake -B /tmp/build -S scripts

    - name: Build/install HDF5
      run: cmake --build /tmp/build

    - name: build & test h5fortran
      run: cmake --workflow default

    - name: install h5fortran
      run: cmake --install build

    - name: example build and test
      run: cmake --workflow default
      working-directory: example
