name: ci_macos

env:
  CTEST_PARALLEL_LEVEL: 4
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  FC: gfortran-11

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_macos.yml"
  release:
    types: [published]

jobs:

  mac-static:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - run: brew install hwloc hdf5-mpi ninja

    - run: cmake --preset multi --install-prefix=${HOME}

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --install build
